### ISSUE TITLE
Circuit UI does not work with tests in create-react-app

### ISSUE THREAD

**Issue by ilyanoskov** [sumup/circuit-ui#207]
In `App.test.js` in a new create-react-app : 

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

import { Button } from '@sumup/circuit-ui';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

I get this error: 

```
 FAIL  src/App.test.js
  ● Test suite failed to run

    /Users/ilyanoskov/Sumup/peop/node_modules/@sumup/circuit-ui/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _omit from'lodash/fp/omit';import head from'lodash/fp/head';import'lodash/fp/last';import clamp from'lodash/fp/clamp';import _isEqual from'lodash/fp/isEqual';import isString from'lodash/fp/isString';import'lodash/fp/isArray';import values from'lodash/fp/values';import toPairs from'lodash/fp/toPairs';import _find from'lodash/fp/find';import _includes from'lodash/fp/includes';import compose from'lodash/fp/compose';import _curry from'lodash/fp/curry';import flow from'lodash/fp/flow';import styled,{css,cx,keyframes,injectGlobal}from'react-emotion';import{size,stripUnit,transparentize,hideVisually}from'polished';import React,{Children,Component,createElement,Fragment,createFactory}from'react';import PropTypes from'prop-types';import _identity from'lodash/fp/identity';import{withTheme}from'emotion-theming';import TextMaskInput from'react-text-mask';

    SyntaxError: Unexpected identifier

      at new Script (vm.js:74:7)
      at Object.<anonymous> (src/App.test.js:5:18)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.639s
Ran all test suites related to changed files.

Watch Usage
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.

```

**Comment by mlent** [comment]
@ilyanoskov @felixjung - I noticed in the create-react-app circuit version that the tests for components area also not running. Can we fix that together somehow?

**Comment by ilyanoskov** [comment]
I have managed to solve this issue by ejecting from create-react-app and adding circuit-ui to ignored dependencies for Jest.

this is what I added to package.json :
```
"transformIgnorePatterns": [
      "/node_modules/(?!(@sumup)/).*/"
    ],
```

may be this is not a right solution long-term, because we can't expect everybody to eject.

**Comment by mlent** [comment]
Should be fixed here: https://github.com/sumup/create-sumup-react-app/pull/1
